### ISSUE TITLE
HTML is not rendered

### ISSUE THREAD

**Issue by cpg** [xw19/RLReview#2]
example, when doing a test comment like this, it renders like below:

```
this is a test https://dl.dropboxusercontent.com/u/364883/RacketLogger/logo-guidelines.pdf
```

i.e. without linking in the html link.

i do not think we want to do a full editor, but maybe markdown or at least something basic.

this is the slippery slope i am afraid of.

**Comment by xw19** [comment]
Redcarpet gem is added html  is now properly rendered along with many differnt options
